### PR TITLE
[Bug Fix] Use Require for Checking Ember Data

### LINKED ISSUE #224: Ember-Data is required to use the DS Error validator - Too Strict for ED 2.6+
In recent versions of Ember Data, validating that Ember Data exists by `self.DS` is no longer effective - because ED imports work like this now:
```
import Model from 'ember-data/model';
import attr from 'ember-data/attr';
```

This error is thrown:
https://github.com/offirgolan/ember-cp-validations/blob/d682193c1bb978ad56b300d38c1297e42aa96ba7/addon/validators/ds-error.js#L10

I'd recommend something like this:
```
try {
  requireModule('ember-data');
} catch {
  throw new Error('Ember-Data is required to use the DS Error validator.');
}
```

That cool?  if so I'll shoot over a PR

### PR DESCRIPTION
**Pull request by offirgolan**
Closes #224

### CODE REVIEW

File: addon/utils/utils.js [hunk 1]
```diff
@@ -4,9 +4,14 @@
  */
 
 import Ember from 'ember';
+import require from 'require';
 
 export function hasEmberData() {
-  return typeof self.DS !== 'undefined';
+  return require.has('ember-data');
```
Comment (alexparker) [inline addon/utils/utils.js]: I'm getting an error here `utils.js Uncaught TypeError: Cannot read property 'has' of undefined` is there a version of ember this is incompatible with? I'm on ember 2.5

Comment (offirgolan) [inline addon/utils/utils.js]: Weird, this has been tested on Ember 1.11 to canary. What version of ember-cli are you on?

/cc @stefanpenner
